[package]
name = "mod_b"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mokio = { version = "0.1.0", path = "../mokio" }
rubicon = { path = "../../rubicon", features = ["import-globals"] }
soprintln = { version = "3.0.0", features = ["print"] }
